apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoidm90cmUtaWRlbnRpZmlhbnQiLCJwYXNzd29yZCI6ImdocF9sdDh6VXNmR1laclhiUVdtWndHMVhzS2tUOXZyUEYyemFTdXkiLCJhdXRoIjoiZG05MGNtVXRhV1JsYm5ScFptbGhiblE2WjJod1gyeDBPSHBWYzJaSFdWcHlXR0pSVjIxYWQwY3hXSE5MYTFRNWRuSlFSako2WVZOMWVRPT0ifX19
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
